service: serverless-python
frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.8
  region: sa-east-1
  timeout: 60
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - s3:*
      Resource: ["*"]

package:
  individually: true
  exclude:
    - "**/*"
  include:
    - "*.py"
    - "maps/**"
    - "pandas"
    - "geopandas"

functions:
  bacias:
    handler: handler.bacias
    events:
      - s3:
          bucket: bucket-docs-nodejs
          event: s3:ObjectCreated:*
          existing: true
          rules:
            - prefix: Eta40/ETA40_m_
            - suffix: .dat

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    zip: true
